// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "../../modbus/modbus.h"
#include "ui.h"
#include <Arduino.h>

void DeskLightSwitch(lv_event_t *e)
{   
    static bool state = true;
    uint16_t data[] = {0x0000};
    const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
    const uint16_t start_address = 32;
    if (state)
    {
        data[0] = 1;
    }
    else
    {
        data[0] = 0;
    }
    modbus_client_set_parameters(data, start_address, num_registers);

    state = !state;
}

void WallLightSwitch(lv_event_t *e)
{
    static bool state = true;
    uint16_t data[] = {0x0000};
    const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
    const uint16_t start_address = 33;
    if (state)
    {
        data[0] = 1;
    }
    else
    {
        data[0] = 0;
    }
    modbus_client_set_parameters(data, start_address, num_registers);

    state = !state;
}

void CircleLedSwitch(lv_event_t *e)
{
    static bool state = true;
    uint16_t data[] = {0x0000};
    const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
    const uint16_t start_address = 34;
    if (state)
    {
        data[0] = 1;
    }
    else
    {
        data[0] = 0;
    }
    modbus_client_set_parameters(data, start_address, num_registers);

    state = !state;
}

void PendantLedSwitch(lv_event_t *e)
{
    static bool state = true;
    uint16_t data[] = {0x0000};
    const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
    const uint16_t start_address = 35;
    if (state)
    {
        data[0] = 1;
    }
    else
    {
        data[0] = 0;
    }
    modbus_client_set_parameters(data, start_address, num_registers);

    state = !state;
}

void CeilingLedSlider(lv_event_t *e)
{
    // Your code here
}

void CeilingLightSlider(lv_event_t *e)
{
    // Your code here
}

void config_set_backlight(lv_event_t *e)
{
    lv_obj_t *slider = lv_event_get_target(e);
    float brightness = 100.0;
    if (slider == ui_configBrightnessSlider)
    {
        brightness = (float) lv_slider_get_value(slider) / 100.0;
        // 0 is off, 0.5 is half and 1 is full brightness.
    }
}