// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "../ui.h"

void ui_config_screen_init(void)
{
    ui_config = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_config, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_config, lv_color_hex(0xB5B5B5), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_config, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_config, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_config, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Header1 = lv_obj_create(ui_config);
    lv_obj_remove_style_all(ui_Header1);
    lv_obj_set_height(ui_Header1, 60);
    lv_obj_set_width(ui_Header1, lv_pct(100));
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, -210);
    lv_obj_set_align(ui_Header1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Header1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0x5A5A5A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Header1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header1, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Header1, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SysInfo1 = lv_obj_create(ui_Header1);
    lv_obj_remove_style_all(ui_SysInfo1);
    lv_obj_set_width(ui_SysInfo1, lv_pct(52));
    lv_obj_set_height(ui_SysInfo1, lv_pct(100));
    lv_obj_set_align(ui_SysInfo1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SysInfo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiDisconnect1 = lv_btn_create(ui_SysInfo1);
    lv_obj_set_width(ui_wifiDisconnect1, 50);
    lv_obj_set_height(ui_wifiDisconnect1, 52);
    lv_obj_set_x(ui_wifiDisconnect1, -20);
    lv_obj_set_y(ui_wifiDisconnect1, 0);
    lv_obj_set_align(ui_wifiDisconnect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiDisconnect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiDisconnect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiDisconnect1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiDisconnect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiDisconnect1, &ui_img_222132382, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnect1 = lv_btn_create(ui_SysInfo1);
    lv_obj_set_width(ui_wifiConnect1, 50);
    lv_obj_set_height(ui_wifiConnect1, 52);
    lv_obj_set_x(ui_wifiConnect1, -20);
    lv_obj_set_y(ui_wifiConnect1, 0);
    lv_obj_set_align(ui_wifiConnect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiConnect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiConnect1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiConnect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiConnect1, &ui_img_364238874, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notification1 = lv_btn_create(ui_SysInfo1);
    lv_obj_set_width(ui_notification1, 50);
    lv_obj_set_height(ui_notification1, 52);
    lv_obj_set_x(ui_notification1, 40);
    lv_obj_set_y(ui_notification1, 0);
    lv_obj_set_align(ui_notification1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notification1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_notification1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_notification1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notification1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_notification1, &ui_img_686816875, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting1 = lv_btn_create(ui_SysInfo1);
    lv_obj_set_width(ui_setting1, 52);
    lv_obj_set_height(ui_setting1, 52);
    lv_obj_set_x(ui_setting1, 96);
    lv_obj_set_y(ui_setting1, 0);
    lv_obj_set_align(ui_setting1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_setting1, &ui_img_887305853, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Zones1 = lv_obj_create(ui_Header1);
    lv_obj_remove_style_all(ui_Zones1);
    lv_obj_set_width(ui_Zones1, lv_pct(46));
    lv_obj_set_height(ui_Zones1, lv_pct(100));
    lv_obj_set_align(ui_Zones1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Zones1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_layoutBtn1 = lv_btn_create(ui_Zones1);
    lv_obj_set_width(ui_layoutBtn1, 52);
    lv_obj_set_height(ui_layoutBtn1, 52);
    lv_obj_set_x(ui_layoutBtn1, -82);
    lv_obj_set_y(ui_layoutBtn1, 0);
    lv_obj_set_align(ui_layoutBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_layoutBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_layoutBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_layoutBtn1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_layoutBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_layoutBtn1, &ui_img_540379319, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zoneDropList1 = lv_dropdown_create(ui_Zones1);
    lv_dropdown_set_options(ui_zoneDropList1,
                            "Vestibule\nLivingroom\nDiningroom\nKitchen\nBathroom\nGuestroom\nOffice\nBedroom");
    lv_obj_set_width(ui_zoneDropList1, 159);
    lv_obj_set_height(ui_zoneDropList1, 40);
    lv_obj_set_x(ui_zoneDropList1, -3);
    lv_obj_set_y(ui_zoneDropList1, -1);
    lv_obj_set_align(ui_zoneDropList1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_zoneDropList1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_zoneDropList1, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_Container1 = lv_obj_create(ui_config);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 468);
    lv_obj_set_height(ui_Container1, 408);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configBrightness = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_configBrightness);
    lv_obj_set_width(ui_configBrightness, 468);
    lv_obj_set_height(ui_configBrightness, lv_pct(30));
    lv_obj_set_x(ui_configBrightness, 0);
    lv_obj_set_y(ui_configBrightness, lv_pct(-35));
    lv_obj_set_align(ui_configBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configBrightness, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_configBrightness, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_configBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_configBrightness, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_configBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_configBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_configBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_configBrightness);
    lv_img_set_src(ui_Image5, &ui_img_1423884986);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image5, -219);
    lv_obj_set_y(ui_Image5, -36);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_configBrightness);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -150);
    lv_obj_set_y(ui_Label1, -36);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Brightness");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_configBrightness);
    lv_img_set_src(ui_Image1, &ui_img_1310322208);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image1, -207);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configBrightnessSlider = lv_slider_create(ui_configBrightness);
    lv_slider_set_range(ui_configBrightnessSlider, 10, 100);
    lv_slider_set_value(ui_configBrightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_configBrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_configBrightnessSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_configBrightnessSlider, 350);
    lv_obj_set_height(ui_configBrightnessSlider, 10);
    lv_obj_set_x(ui_configBrightnessSlider, 1);
    lv_obj_set_y(ui_configBrightnessSlider, 0);
    lv_obj_set_align(ui_configBrightnessSlider, LV_ALIGN_CENTER);


    ui_Image4 = lv_img_create(ui_configBrightness);
    lv_img_set_src(ui_Image4, &ui_img_1658605586);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image4, 206);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_configBrightness);
    lv_obj_set_width(ui_Switch1, 40);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 197);
    lv_obj_set_y(ui_Switch1, 42);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Label3 = lv_label_create(ui_configBrightness);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -150);
    lv_obj_set_y(ui_Label3, 40);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Auto-brightness");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configLanguage = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_configLanguage);
    lv_obj_set_width(ui_configLanguage, 468);
    lv_obj_set_height(ui_configLanguage, lv_pct(14));
    lv_obj_set_x(ui_configLanguage, 0);
    lv_obj_set_y(ui_configLanguage, lv_pct(-12));
    lv_obj_set_align(ui_configLanguage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configLanguage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configLanguage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_configLanguage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_configLanguage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configLanguage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_configLanguage, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_configLanguage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_configLanguage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_configLanguage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_configLanguage);
    lv_img_set_src(ui_Image10, &ui_img_789797763);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image10, -219);
    lv_obj_set_y(ui_Image10, 2);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_configLanguage);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -152);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Language");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_languageDropdownList = lv_dropdown_create(ui_configLanguage);
    lv_dropdown_set_options(ui_languageDropdownList, "Simplified Chinese\nTraditional Chinese\nEnglish (US)");
    lv_obj_set_width(ui_languageDropdownList, 235);
    lv_obj_set_height(ui_languageDropdownList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_languageDropdownList, 98);
    lv_obj_set_y(ui_languageDropdownList, 0);
    lv_obj_set_align(ui_languageDropdownList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_languageDropdownList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_menubg2 = lv_img_create(ui_config);
    lv_img_set_src(ui_menubg2, &ui_img_menu_bg_png);
    lv_obj_set_width(ui_menubg2, lv_pct(100));
    lv_obj_set_height(ui_menubg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menubg2, 0);
    lv_obj_set_y(ui_menubg2, lv_pct(50));
    lv_obj_set_align(ui_menubg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menubg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_setting1, ui_event_setting1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_layoutBtn1, ui_event_layoutBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configBrightnessSlider, ui_event_configBrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_config, ui_event_config, LV_EVENT_ALL, NULL);
    uic_SysInfo = ui_SysInfo1;
    uic_wifiDisconnect = ui_wifiDisconnect1;
    uic_notification = ui_wifiConnect1;
    uic_notification = ui_notification1;
    uic_setting = ui_layoutBtn1;
    uic_zoneDropList = ui_zoneDropList1;
    uic_configBrightness = ui_configBrightness;
    uic_configBrightnessSlider = ui_configBrightnessSlider;
    uic_configLanguage = ui_configLanguage;

}
