// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_main, lv_color_hex(0xB5B5B5), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_main, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_main, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Header = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_Header);
    lv_obj_set_height(ui_Header, 60);
    lv_obj_set_width(ui_Header, lv_pct(100));
    lv_obj_set_x(ui_Header, 0);
    lv_obj_set_y(ui_Header, -210);
    lv_obj_set_align(ui_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Header, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x5A5A5A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Header, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Header, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SysInfo = lv_obj_create(ui_Header);
    lv_obj_remove_style_all(ui_SysInfo);
    lv_obj_set_width(ui_SysInfo, lv_pct(52));
    lv_obj_set_height(ui_SysInfo, lv_pct(100));
    lv_obj_set_align(ui_SysInfo, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SysInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiDisconnect = lv_btn_create(ui_SysInfo);
    lv_obj_set_width(ui_wifiDisconnect, 50);
    lv_obj_set_height(ui_wifiDisconnect, 52);
    lv_obj_set_x(ui_wifiDisconnect, -20);
    lv_obj_set_y(ui_wifiDisconnect, 0);
    lv_obj_set_align(ui_wifiDisconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiDisconnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiDisconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiDisconnect, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiDisconnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiDisconnect, &ui_img_222132382, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnect = lv_btn_create(ui_SysInfo);
    lv_obj_set_width(ui_wifiConnect, 50);
    lv_obj_set_height(ui_wifiConnect, 52);
    lv_obj_set_x(ui_wifiConnect, -20);
    lv_obj_set_y(ui_wifiConnect, 0);
    lv_obj_set_align(ui_wifiConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiConnect, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiConnect, &ui_img_364238874, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notification = lv_btn_create(ui_SysInfo);
    lv_obj_set_width(ui_notification, 50);
    lv_obj_set_height(ui_notification, 52);
    lv_obj_set_x(ui_notification, 40);
    lv_obj_set_y(ui_notification, 0);
    lv_obj_set_align(ui_notification, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notification, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_notification, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_notification, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_notification, &ui_img_686816875, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting = lv_btn_create(ui_SysInfo);
    lv_obj_set_width(ui_setting, 52);
    lv_obj_set_height(ui_setting, 52);
    lv_obj_set_x(ui_setting, 96);
    lv_obj_set_y(ui_setting, 0);
    lv_obj_set_align(ui_setting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_setting, &ui_img_887305853, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Zones = lv_obj_create(ui_Header);
    lv_obj_remove_style_all(ui_Zones);
    lv_obj_set_width(ui_Zones, lv_pct(46));
    lv_obj_set_height(ui_Zones, lv_pct(100));
    lv_obj_set_align(ui_Zones, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Zones, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_layoutBtn = lv_btn_create(ui_Zones);
    lv_obj_set_width(ui_layoutBtn, 52);
    lv_obj_set_height(ui_layoutBtn, 52);
    lv_obj_set_x(ui_layoutBtn, -82);
    lv_obj_set_y(ui_layoutBtn, 0);
    lv_obj_set_align(ui_layoutBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_layoutBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_layoutBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_layoutBtn, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_layoutBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_layoutBtn, &ui_img_540379319, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zoneDropList = lv_dropdown_create(ui_Zones);
    lv_dropdown_set_options(ui_zoneDropList,
                            "Vestibule\nLivingroom\nDiningroom\nKitchen\nBathroom\nGuestroom\nOffice\nBedroom");
    lv_obj_set_width(ui_zoneDropList, 159);
    lv_obj_set_height(ui_zoneDropList, 40);
    lv_obj_set_x(ui_zoneDropList, -3);
    lv_obj_set_y(ui_zoneDropList, -1);
    lv_obj_set_align(ui_zoneDropList, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_zoneDropList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_zoneDropList, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_ContentLight = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_ContentLight);
    lv_obj_set_width(ui_ContentLight, 468);
    lv_obj_set_height(ui_ContentLight, 348);
    lv_obj_set_align(ui_ContentLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContentLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);   /// Flags
    lv_obj_clear_flag(ui_ContentLight, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContentLight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContentLight, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContentLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContentLight, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContentLight, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightSwitch0 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightSwitch0);
    lv_obj_set_width(ui_lightSwitch0, 230);
    lv_obj_set_height(ui_lightSwitch0, lv_pct(25));
    lv_obj_set_x(ui_lightSwitch0, -118);
    lv_obj_set_y(ui_lightSwitch0, lv_pct(-37));
    lv_obj_set_align(ui_lightSwitch0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightSwitch0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightSwitch0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightSwitch0, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightSwitch0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSwitch0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightSwitch0, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightSwitch0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightSwitch0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightSwitch0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_lightSwitch0);
    lv_img_set_src(ui_Image2, &ui_img_1387712441);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image2, -83);
    lv_obj_set_y(ui_Image2, -12);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_lightSwitch0);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -14);
    lv_obj_set_y(ui_Label2, -13);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Desk Light");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_lightSwitch0);
    lv_obj_set_width(ui_Switch3, 40);
    lv_obj_set_height(ui_Switch3, 20);
    lv_obj_set_x(ui_Switch3, -6);
    lv_obj_set_y(ui_Switch3, 24);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_lightSwitch1 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightSwitch1);
    lv_obj_set_width(ui_lightSwitch1, 230);
    lv_obj_set_height(ui_lightSwitch1, lv_pct(25));
    lv_obj_set_x(ui_lightSwitch1, 119);
    lv_obj_set_y(ui_lightSwitch1, lv_pct(-37));
    lv_obj_set_align(ui_lightSwitch1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightSwitch1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightSwitch1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightSwitch1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightSwitch1, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightSwitch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightSwitch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_lightSwitch1);
    lv_img_set_src(ui_Image3, &ui_img_1387712441);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image3, -83);
    lv_obj_set_y(ui_Image3, -12);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_lightSwitch1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -18);
    lv_obj_set_y(ui_Label4, -13);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Wall Light");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_lightSwitch1);
    lv_obj_set_width(ui_Switch4, 40);
    lv_obj_set_height(ui_Switch4, 20);
    lv_obj_set_x(ui_Switch4, -6);
    lv_obj_set_y(ui_Switch4, 24);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_lightSwitch2 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightSwitch2);
    lv_obj_set_width(ui_lightSwitch2, 230);
    lv_obj_set_height(ui_lightSwitch2, lv_pct(25));
    lv_obj_set_x(ui_lightSwitch2, -118);
    lv_obj_set_y(ui_lightSwitch2, lv_pct(-11));
    lv_obj_set_align(ui_lightSwitch2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightSwitch2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightSwitch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightSwitch2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightSwitch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightSwitch2, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightSwitch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightSwitch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_lightSwitch2);
    lv_img_set_src(ui_Image8, &ui_img_1387712441);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image8, -83);
    lv_obj_set_y(ui_Image8, -12);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_lightSwitch2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -14);
    lv_obj_set_y(ui_Label7, -13);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Circle LED");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch7 = lv_switch_create(ui_lightSwitch2);
    lv_obj_set_width(ui_Switch7, 40);
    lv_obj_set_height(ui_Switch7, 20);
    lv_obj_set_x(ui_Switch7, -6);
    lv_obj_set_y(ui_Switch7, 24);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);


    ui_lightSwitch3 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightSwitch3);
    lv_obj_set_width(ui_lightSwitch3, 230);
    lv_obj_set_height(ui_lightSwitch3, lv_pct(25));
    lv_obj_set_x(ui_lightSwitch3, 119);
    lv_obj_set_y(ui_lightSwitch3, lv_pct(-11));
    lv_obj_set_align(ui_lightSwitch3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightSwitch3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightSwitch3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightSwitch3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightSwitch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightSwitch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightSwitch3, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightSwitch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightSwitch3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightSwitch3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_lightSwitch3);
    lv_img_set_src(ui_Image9, &ui_img_1387712441);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image9, -83);
    lv_obj_set_y(ui_Image9, -12);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_lightSwitch3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -26);
    lv_obj_set_y(ui_Label8, -13);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Pendant");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch8 = lv_switch_create(ui_lightSwitch3);
    lv_obj_set_width(ui_Switch8, 40);
    lv_obj_set_height(ui_Switch8, 20);
    lv_obj_set_x(ui_Switch8, -6);
    lv_obj_set_y(ui_Switch8, 24);
    lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);


    ui_lightDimming2 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightDimming2);
    lv_obj_set_width(ui_lightDimming2, 468);
    lv_obj_set_height(ui_lightDimming2, lv_pct(25));
    lv_obj_set_x(ui_lightDimming2, 0);
    lv_obj_set_y(ui_lightDimming2, lv_pct(15));
    lv_obj_set_align(ui_lightDimming2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightDimming2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightDimming2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightDimming2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightDimming2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightDimming2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightDimming2, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightDimming2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightDimming2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightDimming2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_lightDimming2);
    lv_img_set_src(ui_Image6, &ui_img_1387712441);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image6, -200);
    lv_obj_set_y(ui_Image6, -13);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_lightDimming2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -123);
    lv_obj_set_y(ui_Label5, -13);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Ceiling LED");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_lightDimming2);
    lv_obj_set_width(ui_Switch5, 40);
    lv_obj_set_height(ui_Switch5, 20);
    lv_obj_set_x(ui_Switch5, 175);
    lv_obj_set_y(ui_Switch5, -14);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);


    ui_Slider3 = lv_slider_create(ui_lightDimming2);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 396);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, 0);
    lv_obj_set_y(ui_Slider3, 27);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x09377A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider3, lv_color_hex(0xFF0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_lightDimming3 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightDimming3);
    lv_obj_set_width(ui_lightDimming3, 468);
    lv_obj_set_height(ui_lightDimming3, lv_pct(25));
    lv_obj_set_x(ui_lightDimming3, 0);
    lv_obj_set_y(ui_lightDimming3, lv_pct(41));
    lv_obj_set_align(ui_lightDimming3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightDimming3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightDimming3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightDimming3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightDimming3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightDimming3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightDimming3, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightDimming3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightDimming3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightDimming3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_lightDimming3);
    lv_img_set_src(ui_Image7, &ui_img_1387712441);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image7, -200);
    lv_obj_set_y(ui_Image7, -13);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_lightDimming3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -123);
    lv_obj_set_y(ui_Label6, -13);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Ceiling Light");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_lightDimming3);
    lv_obj_set_width(ui_Switch6, 40);
    lv_obj_set_height(ui_Switch6, 20);
    lv_obj_set_x(ui_Switch6, 175);
    lv_obj_set_y(ui_Switch6, -14);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);


    ui_Slider4 = lv_slider_create(ui_lightDimming3);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 396);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, 0);
    lv_obj_set_y(ui_Slider4, 27);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);


    ui_lightDimming4 = lv_obj_create(ui_ContentLight);
    lv_obj_remove_style_all(ui_lightDimming4);
    lv_obj_set_width(ui_lightDimming4, 468);
    lv_obj_set_height(ui_lightDimming4, lv_pct(25));
    lv_obj_set_x(ui_lightDimming4, 0);
    lv_obj_set_y(ui_lightDimming4, lv_pct(67));
    lv_obj_set_align(ui_lightDimming4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightDimming4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lightDimming4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightDimming4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lightDimming4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightDimming4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_lightDimming4, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lightDimming4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lightDimming4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lightDimming4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_lightDimming4);
    lv_img_set_src(ui_Image15, &ui_img_1387712441);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image15, -200);
    lv_obj_set_y(ui_Image15, -13);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_lightDimming4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -123);
    lv_obj_set_y(ui_Label13, -13);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Ceiling Light");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch9 = lv_switch_create(ui_lightDimming4);
    lv_obj_set_width(ui_Switch9, 40);
    lv_obj_set_height(ui_Switch9, 20);
    lv_obj_set_x(ui_Switch9, 175);
    lv_obj_set_y(ui_Switch9, -14);
    lv_obj_set_align(ui_Switch9, LV_ALIGN_CENTER);


    ui_Slider9 = lv_slider_create(ui_lightDimming4);
    lv_slider_set_value(ui_Slider9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider9, 396);
    lv_obj_set_height(ui_Slider9, 10);
    lv_obj_set_x(ui_Slider9, 0);
    lv_obj_set_y(ui_Slider9, 27);
    lv_obj_set_align(ui_Slider9, LV_ALIGN_CENTER);


    ui_ContentScene = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_ContentScene);
    lv_obj_set_width(ui_ContentScene, 468);
    lv_obj_set_height(ui_ContentScene, 348);
    lv_obj_set_align(ui_ContentScene, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContentScene, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_ContentScene, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ContentScene, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_ContentScene, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ContentScene, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContentScene, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContentScene, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContentScene, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContentScene, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneGroup = lv_obj_create(ui_ContentScene);
    lv_obj_remove_style_all(ui_sceneGroup);
    lv_obj_set_width(ui_sceneGroup, 468);
    lv_obj_set_height(ui_sceneGroup, lv_pct(98));
    lv_obj_set_x(ui_sceneGroup, -1);
    lv_obj_set_y(ui_sceneGroup, lv_pct(0));
    lv_obj_set_align(ui_sceneGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sceneGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sceneGroup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sceneGroup, lv_color_hex(0xD4D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneGroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sceneGroup, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sceneGroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_sceneGroup, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_sceneGroup, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sceneGroup, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneGroup, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_sceneHome = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneHome, 52);
    lv_obj_set_height(ui_sceneHome, 52);
    lv_obj_set_x(ui_sceneHome, -160);
    lv_obj_set_y(ui_sceneHome, -90);
    lv_obj_set_align(ui_sceneHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneHome, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneHome, &ui_img_1927447659, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneDinner = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneDinner, 52);
    lv_obj_set_height(ui_sceneDinner, 52);
    lv_obj_set_x(ui_sceneDinner, -50);
    lv_obj_set_y(ui_sceneDinner, -90);
    lv_obj_set_align(ui_sceneDinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneDinner, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneDinner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneDinner, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneDinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneDinner, &ui_img_540303068, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneParty = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneParty, 52);
    lv_obj_set_height(ui_sceneParty, 52);
    lv_obj_set_x(ui_sceneParty, 60);
    lv_obj_set_y(ui_sceneParty, -90);
    lv_obj_set_align(ui_sceneParty, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneParty, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneParty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneParty, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneParty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneParty, &ui_img_1681734448, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneNight = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneNight, 52);
    lv_obj_set_height(ui_sceneNight, 52);
    lv_obj_set_x(ui_sceneNight, -160);
    lv_obj_set_y(ui_sceneNight, 20);
    lv_obj_set_align(ui_sceneNight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneNight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneNight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneNight, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneNight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneNight, &ui_img_496361014, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneReading = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneReading, 52);
    lv_obj_set_height(ui_sceneReading, 52);
    lv_obj_set_x(ui_sceneReading, -50);
    lv_obj_set_y(ui_sceneReading, 20);
    lv_obj_set_align(ui_sceneReading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneReading, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneReading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneReading, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneReading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneReading, &ui_img_255321356, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneLeave = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneLeave, 52);
    lv_obj_set_height(ui_sceneLeave, 52);
    lv_obj_set_x(ui_sceneLeave, 60);
    lv_obj_set_y(ui_sceneLeave, 20);
    lv_obj_set_align(ui_sceneLeave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneLeave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneLeave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneLeave, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneLeave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneLeave, &ui_img_1787871197, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneMorning = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneMorning, 52);
    lv_obj_set_height(ui_sceneMorning, 52);
    lv_obj_set_x(ui_sceneMorning, 160);
    lv_obj_set_y(ui_sceneMorning, -90);
    lv_obj_set_align(ui_sceneMorning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneMorning, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneMorning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneMorning, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneMorning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneMorning, &ui_img_161571896, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneMovie = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneMovie, 52);
    lv_obj_set_height(ui_sceneMovie, 52);
    lv_obj_set_x(ui_sceneMovie, 160);
    lv_obj_set_y(ui_sceneMovie, 20);
    lv_obj_set_align(ui_sceneMovie, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneMovie, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneMovie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneMovie, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneMovie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneMovie, &ui_img_2056880108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneSleep = lv_btn_create(ui_sceneGroup);
    lv_obj_set_width(ui_sceneSleep, 52);
    lv_obj_set_height(ui_sceneSleep, 52);
    lv_obj_set_x(ui_sceneSleep, -160);
    lv_obj_set_y(ui_sceneSleep, 120);
    lv_obj_set_align(ui_sceneSleep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sceneSleep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sceneSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sceneSleep, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneSleep, &ui_img_890010057, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupCurtain = lv_obj_create(ui_main);
    lv_obj_set_width(ui_groupCurtain, 468);
    lv_obj_set_height(ui_groupCurtain, 348);
    lv_obj_set_x(ui_groupCurtain, 0);
    lv_obj_set_y(ui_groupCurtain, -2);
    lv_obj_set_align(ui_groupCurtain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupCurtain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_curtainCtrl1 = lv_obj_create(ui_groupCurtain);
    lv_obj_remove_style_all(ui_curtainCtrl1);
    lv_obj_set_width(ui_curtainCtrl1, 468);
    lv_obj_set_height(ui_curtainCtrl1, lv_pct(25));
    lv_obj_set_x(ui_curtainCtrl1, 0);
    lv_obj_set_y(ui_curtainCtrl1, -130);
    lv_obj_set_align(ui_curtainCtrl1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_curtainCtrl1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtainCtrl1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtainCtrl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainCtrl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_curtainCtrl1, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_curtainCtrl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_curtainCtrl1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_curtainCtrl1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_curtainCtrl1);
    lv_img_set_src(ui_Image11, &ui_img_2064658507);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image11, -200);
    lv_obj_set_y(ui_Image11, -13);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_curtainCtrl1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -98);
    lv_obj_set_y(ui_Label10, -13);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Left Fabric Curtain");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainOpen1 = lv_btn_create(ui_curtainCtrl1);
    lv_obj_set_width(ui_btnCurtainOpen1, 30);
    lv_obj_set_height(ui_btnCurtainOpen1, 24);
    lv_obj_set_x(ui_btnCurtainOpen1, 70);
    lv_obj_set_y(ui_btnCurtainOpen1, -12);
    lv_obj_set_align(ui_btnCurtainOpen1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainOpen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainOpen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainOpen1, &ui_img_1282234856, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainStop1 = lv_btn_create(ui_curtainCtrl1);
    lv_obj_set_width(ui_btnCurtainStop1, 30);
    lv_obj_set_height(ui_btnCurtainStop1, 24);
    lv_obj_set_x(ui_btnCurtainStop1, 125);
    lv_obj_set_y(ui_btnCurtainStop1, -12);
    lv_obj_set_align(ui_btnCurtainStop1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainStop1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainStop1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainStop1, &ui_img_917433972, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainClose1 = lv_btn_create(ui_curtainCtrl1);
    lv_obj_set_width(ui_btnCurtainClose1, 30);
    lv_obj_set_height(ui_btnCurtainClose1, 24);
    lv_obj_set_x(ui_btnCurtainClose1, 180);
    lv_obj_set_y(ui_btnCurtainClose1, -12);
    lv_obj_set_align(ui_btnCurtainClose1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainClose1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainClose1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainClose1, &ui_img_1176167512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider6 = lv_slider_create(ui_curtainCtrl1);
    lv_slider_set_value(ui_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 396);
    lv_obj_set_height(ui_Slider6, 10);
    lv_obj_set_x(ui_Slider6, 0);
    lv_obj_set_y(ui_Slider6, 27);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);


    ui_curtainCtrl = lv_obj_create(ui_groupCurtain);
    lv_obj_remove_style_all(ui_curtainCtrl);
    lv_obj_set_width(ui_curtainCtrl, 468);
    lv_obj_set_height(ui_curtainCtrl, lv_pct(25));
    lv_obj_set_x(ui_curtainCtrl, 0);
    lv_obj_set_y(ui_curtainCtrl, -48);
    lv_obj_set_align(ui_curtainCtrl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_curtainCtrl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtainCtrl, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtainCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_curtainCtrl, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_curtainCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_curtainCtrl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_curtainCtrl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_curtainCtrl);
    lv_img_set_src(ui_Image12, &ui_img_2064658507);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image12, -200);
    lv_obj_set_y(ui_Image12, -13);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_curtainCtrl);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -98);
    lv_obj_set_y(ui_Label9, -13);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Left Gauze Curtain");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainOpen = lv_btn_create(ui_curtainCtrl);
    lv_obj_set_width(ui_btnCurtainOpen, 30);
    lv_obj_set_height(ui_btnCurtainOpen, 24);
    lv_obj_set_x(ui_btnCurtainOpen, 70);
    lv_obj_set_y(ui_btnCurtainOpen, -12);
    lv_obj_set_align(ui_btnCurtainOpen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainOpen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainOpen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainOpen, &ui_img_1282234856, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainStop = lv_btn_create(ui_curtainCtrl);
    lv_obj_set_width(ui_btnCurtainStop, 30);
    lv_obj_set_height(ui_btnCurtainStop, 24);
    lv_obj_set_x(ui_btnCurtainStop, 125);
    lv_obj_set_y(ui_btnCurtainStop, -12);
    lv_obj_set_align(ui_btnCurtainStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainStop, &ui_img_917433972, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainClose = lv_btn_create(ui_curtainCtrl);
    lv_obj_set_width(ui_btnCurtainClose, 30);
    lv_obj_set_height(ui_btnCurtainClose, 24);
    lv_obj_set_x(ui_btnCurtainClose, 180);
    lv_obj_set_y(ui_btnCurtainClose, -12);
    lv_obj_set_align(ui_btnCurtainClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainClose, &ui_img_1176167512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_slider_create(ui_curtainCtrl);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 396);
    lv_obj_set_height(ui_Slider5, 10);
    lv_obj_set_x(ui_Slider5, 0);
    lv_obj_set_y(ui_Slider5, 27);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);


    ui_curtainCtrl2 = lv_obj_create(ui_groupCurtain);
    lv_obj_remove_style_all(ui_curtainCtrl2);
    lv_obj_set_width(ui_curtainCtrl2, 468);
    lv_obj_set_height(ui_curtainCtrl2, lv_pct(25));
    lv_obj_set_x(ui_curtainCtrl2, 0);
    lv_obj_set_y(ui_curtainCtrl2, 34);
    lv_obj_set_align(ui_curtainCtrl2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_curtainCtrl2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtainCtrl2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtainCtrl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainCtrl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_curtainCtrl2, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_curtainCtrl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_curtainCtrl2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_curtainCtrl2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_curtainCtrl2);
    lv_img_set_src(ui_Image13, &ui_img_2064658507);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image13, -200);
    lv_obj_set_y(ui_Image13, -13);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_curtainCtrl2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -92);
    lv_obj_set_y(ui_Label11, -13);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Right Gauze Curtain");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainOpen2 = lv_btn_create(ui_curtainCtrl2);
    lv_obj_set_width(ui_btnCurtainOpen2, 30);
    lv_obj_set_height(ui_btnCurtainOpen2, 24);
    lv_obj_set_x(ui_btnCurtainOpen2, 70);
    lv_obj_set_y(ui_btnCurtainOpen2, -12);
    lv_obj_set_align(ui_btnCurtainOpen2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainOpen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainOpen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainOpen2, &ui_img_1282234856, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainStop2 = lv_btn_create(ui_curtainCtrl2);
    lv_obj_set_width(ui_btnCurtainStop2, 30);
    lv_obj_set_height(ui_btnCurtainStop2, 24);
    lv_obj_set_x(ui_btnCurtainStop2, 125);
    lv_obj_set_y(ui_btnCurtainStop2, -12);
    lv_obj_set_align(ui_btnCurtainStop2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainStop2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainStop2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainStop2, &ui_img_917433972, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainClose2 = lv_btn_create(ui_curtainCtrl2);
    lv_obj_set_width(ui_btnCurtainClose2, 30);
    lv_obj_set_height(ui_btnCurtainClose2, 24);
    lv_obj_set_x(ui_btnCurtainClose2, 180);
    lv_obj_set_y(ui_btnCurtainClose2, -12);
    lv_obj_set_align(ui_btnCurtainClose2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainClose2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainClose2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainClose2, &ui_img_1176167512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7 = lv_slider_create(ui_curtainCtrl2);
    lv_slider_set_value(ui_Slider7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 396);
    lv_obj_set_height(ui_Slider7, 10);
    lv_obj_set_x(ui_Slider7, 0);
    lv_obj_set_y(ui_Slider7, 27);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_CENTER);


    ui_curtainCtrl3 = lv_obj_create(ui_groupCurtain);
    lv_obj_remove_style_all(ui_curtainCtrl3);
    lv_obj_set_width(ui_curtainCtrl3, 468);
    lv_obj_set_height(ui_curtainCtrl3, lv_pct(25));
    lv_obj_set_x(ui_curtainCtrl3, 0);
    lv_obj_set_y(ui_curtainCtrl3, 116);
    lv_obj_set_align(ui_curtainCtrl3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_curtainCtrl3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtainCtrl3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtainCtrl3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtainCtrl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_curtainCtrl3, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_curtainCtrl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_curtainCtrl3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_curtainCtrl3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_curtainCtrl3);
    lv_img_set_src(ui_Image14, &ui_img_2064658507);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image14, -200);
    lv_obj_set_y(ui_Image14, -13);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_curtainCtrl3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -92);
    lv_obj_set_y(ui_Label12, -13);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Right Gauze Curtain");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainOpen3 = lv_btn_create(ui_curtainCtrl3);
    lv_obj_set_width(ui_btnCurtainOpen3, 30);
    lv_obj_set_height(ui_btnCurtainOpen3, 24);
    lv_obj_set_x(ui_btnCurtainOpen3, 70);
    lv_obj_set_y(ui_btnCurtainOpen3, -12);
    lv_obj_set_align(ui_btnCurtainOpen3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainOpen3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainOpen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainOpen3, &ui_img_1282234856, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainStop3 = lv_btn_create(ui_curtainCtrl3);
    lv_obj_set_width(ui_btnCurtainStop3, 30);
    lv_obj_set_height(ui_btnCurtainStop3, 24);
    lv_obj_set_x(ui_btnCurtainStop3, 125);
    lv_obj_set_y(ui_btnCurtainStop3, -12);
    lv_obj_set_align(ui_btnCurtainStop3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainStop3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainStop3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainStop3, &ui_img_917433972, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCurtainClose3 = lv_btn_create(ui_curtainCtrl3);
    lv_obj_set_width(ui_btnCurtainClose3, 30);
    lv_obj_set_height(ui_btnCurtainClose3, 24);
    lv_obj_set_x(ui_btnCurtainClose3, 180);
    lv_obj_set_y(ui_btnCurtainClose3, -12);
    lv_obj_set_align(ui_btnCurtainClose3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCurtainClose3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCurtainClose3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnCurtainClose3, &ui_img_1176167512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider8 = lv_slider_create(ui_curtainCtrl3);
    lv_slider_set_value(ui_Slider8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider8, 396);
    lv_obj_set_height(ui_Slider8, 10);
    lv_obj_set_x(ui_Slider8, 0);
    lv_obj_set_y(ui_Slider8, 27);
    lv_obj_set_align(ui_Slider8, LV_ALIGN_CENTER);


    ui_ContentHVAC = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_ContentHVAC);
    lv_obj_set_width(ui_ContentHVAC, 468);
    lv_obj_set_height(ui_ContentHVAC, 348);
    lv_obj_set_align(ui_ContentHVAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_ContentHVAC, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ContentHVAC, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_ContentHVAC, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ContentHVAC, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContentHVAC, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContentHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContentHVAC, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContentHVAC, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HVAC = lv_obj_create(ui_ContentHVAC);
    lv_obj_remove_style_all(ui_HVAC);
    lv_obj_set_width(ui_HVAC, 464);
    lv_obj_set_height(ui_HVAC, 344);
    lv_obj_set_x(ui_HVAC, 0);
    lv_obj_set_y(ui_HVAC, -6);
    lv_obj_set_align(ui_HVAC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HVAC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HVAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_HVAC);
    lv_obj_set_width(ui_Arc1, 240);
    lv_obj_set_height(ui_Arc1, 240);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, -24);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 16, 30);
    lv_arc_set_value(ui_Arc1, 24);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xF61E1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xDBF00B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x38AF3A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_functionName = lv_label_create(ui_HVAC);
    lv_obj_set_width(ui_functionName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_functionName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_functionName, 2);
    lv_obj_set_y(ui_functionName, -80);
    lv_obj_set_align(ui_functionName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_functionName, "Thermostat");
    lv_obj_set_style_text_color(ui_functionName, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_functionName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_functionName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_HVAC);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, 2);
    lv_obj_set_y(ui_Temp, -22);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "18.4");
    lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMinus = lv_btn_create(ui_HVAC);
    lv_obj_set_width(ui_btnMinus, 40);
    lv_obj_set_height(ui_btnMinus, 40);
    lv_obj_set_x(ui_btnMinus, -80);
    lv_obj_set_y(ui_btnMinus, 108);
    lv_obj_set_align(ui_btnMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnMinus, &ui_img_1729470306, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPlus = lv_btn_create(ui_HVAC);
    lv_obj_set_width(ui_btnPlus, 40);
    lv_obj_set_height(ui_btnPlus, 40);
    lv_obj_set_x(ui_btnPlus, 81);
    lv_obj_set_y(ui_btnPlus, 108);
    lv_obj_set_align(ui_btnPlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_btnPlus, &ui_img_414704204, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_onoff = lv_switch_create(ui_HVAC);
    lv_obj_set_width(ui_onoff, 85);
    lv_obj_set_height(ui_onoff, 36);
    lv_obj_set_x(ui_onoff, 1);
    lv_obj_set_y(ui_onoff, 68);
    lv_obj_set_align(ui_onoff, LV_ALIGN_CENTER);


    ui_modeIcon = lv_img_create(ui_HVAC);
    lv_img_set_src(ui_modeIcon, &ui_img_1735427615);
    lv_obj_set_width(ui_modeIcon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_modeIcon, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_modeIcon, -174);
    lv_obj_set_y(ui_modeIcon, 68);
    lv_obj_set_align(ui_modeIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_modeIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_modeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_modeSelect = lv_roller_create(ui_HVAC);
    lv_roller_set_options(ui_modeSelect, "Cool\nWarm\nVent\nQuiet\nDry\nEco", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_modeSelect, 80);
    lv_obj_set_height(ui_modeSelect, 36);
    lv_obj_set_x(ui_modeSelect, -173);
    lv_obj_set_y(ui_modeSelect, 108);
    lv_obj_set_align(ui_modeSelect, LV_ALIGN_CENTER);

    ui_fanspeedIcon = lv_img_create(ui_HVAC);
    lv_img_set_src(ui_fanspeedIcon, &ui_img_2040129323);
    lv_obj_set_width(ui_fanspeedIcon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_fanspeedIcon, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_fanspeedIcon, 175);
    lv_obj_set_y(ui_fanspeedIcon, 68);
    lv_obj_set_align(ui_fanspeedIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fanspeedIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fanspeedIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fanspeedSelect = lv_roller_create(ui_HVAC);
    lv_roller_set_options(ui_fanspeedSelect, "Auto\nI\nII\nIII\nIIII\nIIIII", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_fanspeedSelect, 80);
    lv_obj_set_height(ui_fanspeedSelect, 36);
    lv_obj_set_x(ui_fanspeedSelect, 176);
    lv_obj_set_y(ui_fanspeedSelect, 108);
    lv_obj_set_align(ui_fanspeedSelect, LV_ALIGN_CENTER);

    ui_GroupBlank = lv_obj_create(ui_main);
    lv_obj_set_width(ui_GroupBlank, 468);
    lv_obj_set_height(ui_GroupBlank, 348);
    lv_obj_set_x(ui_GroupBlank, 0);
    lv_obj_set_y(ui_GroupBlank, -2);
    lv_obj_set_align(ui_GroupBlank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_GroupBlank, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MTechSlogan = lv_label_create(ui_GroupBlank);
    lv_obj_set_width(ui_MTechSlogan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MTechSlogan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MTechSlogan, 2);
    lv_obj_set_y(ui_MTechSlogan, -22);
    lv_obj_set_align(ui_MTechSlogan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MTechSlogan, "Design by M-Tech");
    lv_obj_set_style_text_color(ui_MTechSlogan, lv_color_hex(0x00FF2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MTechSlogan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MTechSlogan, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nav1 = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_Nav1);
    lv_obj_set_width(ui_Nav1, 480);
    lv_obj_set_height(ui_Nav1, 60);
    lv_obj_set_x(ui_Nav1, 0);
    lv_obj_set_y(ui_Nav1, 210);
    lv_obj_set_align(ui_Nav1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Nav1, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_Nav1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Nav1, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Nav1, LV_DIR_HOR);
    lv_obj_set_style_border_color(ui_Nav1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Nav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Nav1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Nav1, lv_color_hex(0x38AF3A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Nav1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_menuLight1 = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuLight1);
    lv_obj_set_height(ui_menuLight1, 60);
    lv_obj_set_width(ui_menuLight1, lv_pct(25));
    lv_obj_set_x(ui_menuLight1, -180);
    lv_obj_set_y(ui_menuLight1, 0);
    lv_obj_set_align(ui_menuLight1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuLight1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuLight1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuLight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuLight1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuLight1, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuLight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuLight1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_menuLight1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Btn6 = lv_btn_create(ui_menuLight1);
    lv_obj_set_width(ui_Btn6, lv_pct(100));
    lv_obj_set_height(ui_Btn6, lv_pct(100));
    lv_obj_set_align(ui_Btn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn6, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn6, &ui_img_591590446, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn6, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected6 = lv_img_create(ui_Btn6);
    lv_img_set_src(ui_menuSelected6, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected6, 37);
    lv_obj_set_y(ui_menuSelected6, 40);
    lv_obj_add_flag(ui_menuSelected6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuScene1 = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuScene1);
    lv_obj_set_height(ui_menuScene1, 60);
    lv_obj_set_width(ui_menuScene1, lv_pct(25));
    lv_obj_set_x(ui_menuScene1, -60);
    lv_obj_set_y(ui_menuScene1, 0);
    lv_obj_set_align(ui_menuScene1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuScene1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuScene1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuScene1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuScene1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuScene1, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuScene1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuScene1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn7 = lv_btn_create(ui_menuScene1);
    lv_obj_set_width(ui_Btn7, lv_pct(100));
    lv_obj_set_height(ui_Btn7, lv_pct(100));
    lv_obj_set_align(ui_Btn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn7, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn7, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn7, &ui_img_2067470297, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn7, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn7, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn7, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected7 = lv_img_create(ui_Btn7);
    lv_img_set_src(ui_menuSelected7, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected7, 37);
    lv_obj_set_y(ui_menuSelected7, 40);
    lv_obj_add_flag(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuCurtain1 = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuCurtain1);
    lv_obj_set_height(ui_menuCurtain1, 60);
    lv_obj_set_width(ui_menuCurtain1, lv_pct(25));
    lv_obj_set_x(ui_menuCurtain1, 60);
    lv_obj_set_y(ui_menuCurtain1, 0);
    lv_obj_set_align(ui_menuCurtain1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuCurtain1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuCurtain1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuCurtain1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuCurtain1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuCurtain1, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuCurtain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuCurtain1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn8 = lv_btn_create(ui_menuCurtain1);
    lv_obj_set_width(ui_Btn8, lv_pct(100));
    lv_obj_set_height(ui_Btn8, lv_pct(100));
    lv_obj_set_align(ui_Btn8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn8, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn8, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn8, &ui_img_2032833556, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn8, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn8, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn8, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn8, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected8 = lv_img_create(ui_Btn8);
    lv_img_set_src(ui_menuSelected8, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected8, 37);
    lv_obj_set_y(ui_menuSelected8, 40);
    lv_obj_add_flag(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuHVAC1 = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuHVAC1);
    lv_obj_set_height(ui_menuHVAC1, 60);
    lv_obj_set_width(ui_menuHVAC1, lv_pct(25));
    lv_obj_set_x(ui_menuHVAC1, 180);
    lv_obj_set_y(ui_menuHVAC1, 0);
    lv_obj_set_align(ui_menuHVAC1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuHVAC1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuHVAC1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuHVAC1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuHVAC1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuHVAC1, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuHVAC1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuHVAC1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn9 = lv_btn_create(ui_menuHVAC1);
    lv_obj_set_width(ui_Btn9, lv_pct(100));
    lv_obj_set_height(ui_Btn9, lv_pct(100));
    lv_obj_set_align(ui_Btn9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn9, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn9, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn9, &ui_img_1220919042, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn9, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn9, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn9, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected9 = lv_img_create(ui_Btn9);
    lv_img_set_src(ui_menuSelected9, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected9, 37);
    lv_obj_set_y(ui_menuSelected9, 40);
    lv_obj_add_flag(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuMusic1 = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuMusic1);
    lv_obj_set_height(ui_menuMusic1, 60);
    lv_obj_set_width(ui_menuMusic1, lv_pct(25));
    lv_obj_set_x(ui_menuMusic1, 300);
    lv_obj_set_y(ui_menuMusic1, 0);
    lv_obj_set_align(ui_menuMusic1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuMusic1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuMusic1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuMusic1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Btn10 = lv_btn_create(ui_menuMusic1);
    lv_obj_set_width(ui_Btn10, lv_pct(100));
    lv_obj_set_height(ui_Btn10, lv_pct(100));
    lv_obj_set_align(ui_Btn10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn10, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn10, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn10, &ui_img_1742922419, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn10, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn10, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn10, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected10 = lv_img_create(ui_Btn10);
    lv_img_set_src(ui_menuSelected10, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected10, 37);
    lv_obj_set_y(ui_menuSelected10, 40);
    lv_obj_add_flag(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuSecure = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuSecure);
    lv_obj_set_height(ui_menuSecure, 60);
    lv_obj_set_width(ui_menuSecure, lv_pct(25));
    lv_obj_set_x(ui_menuSecure, 420);
    lv_obj_set_y(ui_menuSecure, 0);
    lv_obj_set_align(ui_menuSecure, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuSecure, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuSecure, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuSecure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuSecure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menuSecure, &ui_img_84168725, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuSecure, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuSecure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuSecure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn11 = lv_btn_create(ui_menuSecure);
    lv_obj_set_width(ui_Btn11, lv_pct(100));
    lv_obj_set_height(ui_Btn11, lv_pct(100));
    lv_obj_set_align(ui_Btn11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn11, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn11, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn11, &ui_img_84168725, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn11, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn11, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn11, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn11, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn11, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected11 = lv_img_create(ui_Btn11);
    lv_img_set_src(ui_menuSelected11, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected11, 37);
    lv_obj_set_y(ui_menuSelected11, 40);
    lv_obj_add_flag(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuEnv = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuEnv);
    lv_obj_set_height(ui_menuEnv, 60);
    lv_obj_set_width(ui_menuEnv, lv_pct(25));
    lv_obj_set_x(ui_menuEnv, 540);
    lv_obj_set_y(ui_menuEnv, 0);
    lv_obj_set_align(ui_menuEnv, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuEnv, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuEnv, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuEnv, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuEnv, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuEnv, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuEnv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuEnv, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn13 = lv_btn_create(ui_menuEnv);
    lv_obj_set_width(ui_Btn13, lv_pct(100));
    lv_obj_set_height(ui_Btn13, lv_pct(100));
    lv_obj_set_align(ui_Btn13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn13, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn13, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn13, &ui_img_402352260, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn13, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn13, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn13, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn13, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected13 = lv_img_create(ui_Btn13);
    lv_img_set_src(ui_menuSelected13, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected13, 37);
    lv_obj_set_y(ui_menuSelected13, 40);
    lv_obj_add_flag(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuEnergy = lv_obj_create(ui_Nav1);
    lv_obj_remove_style_all(ui_menuEnergy);
    lv_obj_set_height(ui_menuEnergy, 60);
    lv_obj_set_width(ui_menuEnergy, lv_pct(25));
    lv_obj_set_x(ui_menuEnergy, 660);
    lv_obj_set_y(ui_menuEnergy, 0);
    lv_obj_set_align(ui_menuEnergy, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuEnergy, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menuEnergy, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menuEnergy, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuEnergy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menuEnergy, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menuEnergy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menuEnergy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn14 = lv_btn_create(ui_menuEnergy);
    lv_obj_set_width(ui_Btn14, lv_pct(100));
    lv_obj_set_height(ui_Btn14, lv_pct(100));
    lv_obj_set_align(ui_Btn14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Btn14, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Btn14, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Btn14, &ui_img_1188028765, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn14, lv_color_hex(0x888686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Btn14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Btn14, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn14, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn14, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btn14, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuSelected14 = lv_img_create(ui_Btn14);
    lv_img_set_src(ui_menuSelected14, &ui_img_menu_selected_png);
    lv_obj_set_width(ui_menuSelected14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSelected14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuSelected14, 37);
    lv_obj_set_y(ui_menuSelected14, 40);
    lv_obj_add_flag(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menuSelected14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menubg1 = lv_img_create(ui_main);
    lv_img_set_src(ui_menubg1, &ui_img_menu_bg_png);
    lv_obj_set_width(ui_menubg1, lv_pct(100));
    lv_obj_set_height(ui_menubg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menubg1, 0);
    lv_obj_set_y(ui_menubg1, lv_pct(50));
    lv_obj_set_align(ui_menubg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menubg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_layoutBtn, ui_event_layoutBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch8, ui_event_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightDimming2, ui_event_lightDimming2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightDimming3, ui_event_lightDimming3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch9, ui_event_Switch9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn6, ui_event_Btn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn7, ui_event_Btn7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn8, ui_event_Btn8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn9, ui_event_Btn9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn10, ui_event_Btn10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn11, ui_event_Btn11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn13, ui_event_Btn13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn14, ui_event_Btn14, LV_EVENT_ALL, NULL);
    uic_Header = ui_Header;
    uic_SysInfo = ui_SysInfo;
    uic_wifiDisconnect = ui_wifiDisconnect;
    uic_wifiConnect = ui_wifiConnect;
    uic_notification = ui_notification;
    uic_setting = ui_setting;
    uic_Zones = ui_Zones;
    uic_setting = ui_layoutBtn;
    uic_zoneDropList = ui_zoneDropList;
    uic_Content = ui_ContentLight;
    uic_lightSwitch0 = ui_lightSwitch0;
    uic_lightSwitch1 = ui_lightSwitch1;
    uic_lightSwitch0 = ui_lightSwitch2;
    uic_lightSwitch1 = ui_lightSwitch3;
    uic_lightDimming1 = ui_lightDimming2;
    uic_lightDimming1 = ui_lightDimming3;
    uic_lightDimming1 = ui_lightDimming4;
    uic_Content = ui_ContentScene;
    uic_lightDimming0 = ui_sceneGroup;
    uic_sceneHome = ui_sceneHome;
    uic_setting = ui_sceneDinner;
    uic_setting = ui_sceneParty;
    uic_setting = ui_sceneNight;
    uic_setting = ui_sceneReading;
    uic_setting = ui_sceneLeave;
    uic_setting = ui_sceneMorning;
    uic_setting = ui_sceneMovie;
    uic_setting = ui_sceneSleep;
    uic_lightDimming1 = ui_curtainCtrl1;
    uic_lightDimming1 = ui_curtainCtrl;
    uic_curtainCtrl2 = ui_curtainCtrl2;
    uic_curtainCtrl2 = ui_curtainCtrl3;
    uic_Content = ui_ContentHVAC;
    uic_functionName = ui_functionName;
    uic_Temp = ui_Temp;
    uic_modeSelect = ui_modeSelect;
    uic_fanspeedSelect = ui_fanspeedSelect;
    uic_MTechSlogan = ui_MTechSlogan;
    uic_Nav1 = ui_Nav1;
    uic_menuLight = ui_menuLight1;
    uic_Btn = ui_Btn6;
    uic_menuScene = ui_menuScene1;
    uic_Btn = ui_Btn7;
    uic_menuCurtain = ui_menuCurtain1;
    uic_Btn = ui_Btn8;
    uic_menuMedia = ui_menuHVAC1;
    uic_Btn = ui_Btn9;
    uic_menuMedia = ui_menuMusic1;
    uic_Btn = ui_Btn10;
    uic_menuSecure = ui_menuSecure;
    uic_Btn = ui_Btn11;
    uic_menuSecure = ui_menuEnv;
    uic_Btn = ui_Btn13;
    uic_menuEnergy = ui_menuEnergy;
    uic_Btn = ui_Btn14;

}
