// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void contentSwitching_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t * ui_main;
lv_obj_t * ui_Header;
lv_obj_t * ui_SysInfo;
lv_obj_t * ui_wifiDisconnect;
lv_obj_t * ui_wifiConnect;
lv_obj_t * ui_notification;
void ui_event_setting(lv_event_t * e);
lv_obj_t * ui_setting;
lv_obj_t * ui_Zones;
void ui_event_layoutBtn(lv_event_t * e);
lv_obj_t * ui_layoutBtn;
lv_obj_t * ui_zoneDropList;
lv_obj_t * ui_ContentLight;
lv_obj_t * ui_lightSwitch0;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_lightSwitch1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_lightSwitch2;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Switch7;
lv_obj_t * ui_lightSwitch3;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Switch8;
lv_obj_t * ui_lightDimming2;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Slider3;
lv_obj_t * ui_lightDimming3;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label6;
void ui_event_Switch6(lv_event_t * e);
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Slider4;
lv_obj_t * ui_lightDimming4;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label13;
void ui_event_Switch9(lv_event_t * e);
lv_obj_t * ui_Switch9;
lv_obj_t * ui_Slider9;
lv_obj_t * ui_ContentScene;
lv_obj_t * ui_sceneGroup;
lv_obj_t * ui_sceneHome;
lv_obj_t * ui_sceneDinner;
lv_obj_t * ui_sceneParty;
lv_obj_t * ui_sceneNight;
lv_obj_t * ui_sceneReading;
lv_obj_t * ui_sceneLeave;
lv_obj_t * ui_sceneMorning;
lv_obj_t * ui_sceneMovie;
lv_obj_t * ui_sceneSleep;
lv_obj_t * ui_groupCurtain;
lv_obj_t * ui_curtainCtrl1;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label10;
lv_obj_t * ui_btnCurtainOpen1;
lv_obj_t * ui_btnCurtainStop1;
lv_obj_t * ui_btnCurtainClose1;
lv_obj_t * ui_Slider6;
lv_obj_t * ui_curtainCtrl;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_btnCurtainOpen;
lv_obj_t * ui_btnCurtainStop;
lv_obj_t * ui_btnCurtainClose;
lv_obj_t * ui_Slider5;
lv_obj_t * ui_curtainCtrl2;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label11;
lv_obj_t * ui_btnCurtainOpen2;
lv_obj_t * ui_btnCurtainStop2;
lv_obj_t * ui_btnCurtainClose2;
lv_obj_t * ui_Slider7;
lv_obj_t * ui_curtainCtrl3;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label12;
lv_obj_t * ui_btnCurtainOpen3;
lv_obj_t * ui_btnCurtainStop3;
lv_obj_t * ui_btnCurtainClose3;
lv_obj_t * ui_Slider8;
lv_obj_t * ui_ContentHVAC;
lv_obj_t * ui_HVAC;
void ui_event_Arc1(lv_event_t * e);
lv_obj_t * ui_Arc1;
lv_obj_t * ui_functionName;
lv_obj_t * ui_Temp;
lv_obj_t * ui_btnMinus;
lv_obj_t * ui_btnPlus;
lv_obj_t * ui_onoff;
lv_obj_t * ui_modeIcon;
lv_obj_t * ui_modeSelect;
lv_obj_t * ui_fanspeedIcon;
lv_obj_t * ui_fanspeedSelect;
lv_obj_t * ui_GroupBlank;
lv_obj_t * ui_MTechSlogan;
lv_obj_t * ui_Nav1;
lv_obj_t * ui_menuLight1;
void ui_event_Btn6(lv_event_t * e);
lv_obj_t * ui_Btn6;
lv_obj_t * ui_menuSelected6;
lv_obj_t * ui_menuScene1;
void ui_event_Btn7(lv_event_t * e);
lv_obj_t * ui_Btn7;
lv_obj_t * ui_menuSelected7;
lv_obj_t * ui_menuCurtain1;
void ui_event_Btn8(lv_event_t * e);
lv_obj_t * ui_Btn8;
lv_obj_t * ui_menuSelected8;
lv_obj_t * ui_menuHVAC1;
void ui_event_Btn9(lv_event_t * e);
lv_obj_t * ui_Btn9;
lv_obj_t * ui_menuSelected9;
lv_obj_t * ui_menuMusic1;
void ui_event_Btn10(lv_event_t * e);
lv_obj_t * ui_Btn10;
lv_obj_t * ui_menuSelected10;
lv_obj_t * ui_menuSecure;
void ui_event_Btn11(lv_event_t * e);
lv_obj_t * ui_Btn11;
lv_obj_t * ui_menuSelected11;
lv_obj_t * ui_menuEnv;
void ui_event_Btn13(lv_event_t * e);
lv_obj_t * ui_Btn13;
lv_obj_t * ui_menuSelected13;
lv_obj_t * ui_menuEnergy;
void ui_event_Btn14(lv_event_t * e);
lv_obj_t * ui_Btn14;
lv_obj_t * ui_menuSelected14;
lv_obj_t * ui_menubg1;
// CUSTOM VARIABLES
lv_obj_t * uic_Header;
lv_obj_t * uic_SysInfo;
lv_obj_t * uic_wifiDisconnect;
lv_obj_t * uic_wifiConnect;
lv_obj_t * uic_notification;
lv_obj_t * uic_setting;
lv_obj_t * uic_Zones;
lv_obj_t * uic_setting;
lv_obj_t * uic_zoneDropList;
lv_obj_t * uic_Content;
lv_obj_t * uic_lightSwitch0;
lv_obj_t * uic_lightSwitch1;
lv_obj_t * uic_lightSwitch0;
lv_obj_t * uic_lightSwitch1;
lv_obj_t * uic_lightDimming1;
lv_obj_t * uic_lightDimming1;
lv_obj_t * uic_lightDimming1;
lv_obj_t * uic_Content;
lv_obj_t * uic_lightDimming0;
lv_obj_t * uic_sceneHome;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_setting;
lv_obj_t * uic_lightDimming1;
lv_obj_t * uic_lightDimming1;
lv_obj_t * uic_curtainCtrl2;
lv_obj_t * uic_curtainCtrl2;
lv_obj_t * uic_Content;
lv_obj_t * uic_functionName;
lv_obj_t * uic_Temp;
lv_obj_t * uic_modeSelect;
lv_obj_t * uic_fanspeedSelect;
lv_obj_t * uic_MTechSlogan;
lv_obj_t * uic_Nav1;
lv_obj_t * uic_menuLight;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuScene;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuCurtain;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuMedia;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuMedia;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuSecure;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuSecure;
lv_obj_t * uic_Btn;
lv_obj_t * uic_menuEnergy;
lv_obj_t * uic_Btn;


// SCREEN: ui_config
void ui_config_screen_init(void);
void ui_event_config(lv_event_t * e);
lv_obj_t * ui_config;
lv_obj_t * ui_Header1;
lv_obj_t * ui_SysInfo1;
lv_obj_t * ui_wifiDisconnect1;
lv_obj_t * ui_wifiConnect1;
lv_obj_t * ui_notification1;
void ui_event_setting1(lv_event_t * e);
lv_obj_t * ui_setting1;
lv_obj_t * ui_Zones1;
void ui_event_layoutBtn1(lv_event_t * e);
lv_obj_t * ui_layoutBtn1;
lv_obj_t * ui_zoneDropList1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_configBrightness;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
void ui_event_configBrightnessSlider(lv_event_t * e);
lv_obj_t * ui_configBrightnessSlider;
lv_obj_t * ui_Image4;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_configLanguage;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label14;
lv_obj_t * ui_languageDropdownList;
lv_obj_t * ui_menubg2;
// CUSTOM VARIABLES
lv_obj_t * uic_SysInfo;
lv_obj_t * uic_wifiDisconnect;
lv_obj_t * uic_notification;
lv_obj_t * uic_notification;
lv_obj_t * uic_setting;
lv_obj_t * uic_zoneDropList;
lv_obj_t * uic_configBrightness;
lv_obj_t * uic_configBrightnessSlider;
lv_obj_t * uic_configLanguage;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_351488482[1] = {&ui_img_2064658507};
const lv_img_dsc_t * ui_imgset_1604542579[1] = {&ui_img_1176167512};
const lv_img_dsc_t * ui_imgset_1104495342[1] = {&ui_img_2032833556};
const lv_img_dsc_t * ui_imgset_328519917[1] = {&ui_img_1282234856};
const lv_img_dsc_t * ui_imgset_1075893097[1] = {&ui_img_917433972};
const lv_img_dsc_t * ui_imgset_1981450097[1] = {&ui_img_1188028765};
const lv_img_dsc_t * ui_imgset_1379816406[1] = {&ui_img_402352260};
const lv_img_dsc_t * ui_imgset_1894994391[1] = {&ui_img_2040129323};
const lv_img_dsc_t * ui_imgset_1826338332[1] = {&ui_img_1220919042};
const lv_img_dsc_t * ui_imgset_710967466[1] = {&ui_img_686816875};
const lv_img_dsc_t * ui_imgset_578450504[1] = {&ui_img_540379319};
const lv_img_dsc_t * ui_imgset_1497443836[1] = {&ui_img_1387712441};
const lv_img_dsc_t * ui_imgset_1812689140[1] = {&ui_img_591590446};
const lv_img_dsc_t * ui_imgset_781618292[1] = {&ui_img_1729470306};
const lv_img_dsc_t * ui_imgset_1025241861[1] = {&ui_img_1735427615};
const lv_img_dsc_t * ui_imgset_575017621[1] = {&ui_img_1742922419};
const lv_img_dsc_t * ui_imgset_406751859[1] = {&ui_img_222132382};
const lv_img_dsc_t * ui_imgset_801595910[1] = {&ui_img_414704204};
const lv_img_dsc_t * ui_imgset_2014007949[1] = {&ui_img_540303068};
const lv_img_dsc_t * ui_imgset_694933266[1] = {&ui_img_1927447659};
const lv_img_dsc_t * ui_imgset_2017136506[1] = {&ui_img_1787871197};
const lv_img_dsc_t * ui_imgset_2049001895[1] = {&ui_img_161571896};
const lv_img_dsc_t * ui_imgset_1040610969[1] = {&ui_img_2056880108};
const lv_img_dsc_t * ui_imgset_1110970233[1] = {&ui_img_496361014};
const lv_img_dsc_t * ui_imgset_1200937475[1] = {&ui_img_1681734448};
const lv_img_dsc_t * ui_imgset_2039982581[1] = {&ui_img_255321356};
const lv_img_dsc_t * ui_imgset_731347651[1] = {&ui_img_2067470297};
const lv_img_dsc_t * ui_imgset_1008528466[1] = {&ui_img_890010057};
const lv_img_dsc_t * ui_imgset_724146983[1] = {&ui_img_84168725};
const lv_img_dsc_t * ui_imgset_1771410100[1] = {&ui_img_887305853};
const lv_img_dsc_t * ui_imgset_535857063[1] = {&ui_img_364238874};
const lv_img_dsc_t * ui_imgset_1986574229[1] = {&ui_img_1658605586};
const lv_img_dsc_t * ui_imgset_1196421701[1] = {&ui_img_1310322208};
const lv_img_dsc_t * ui_imgset_619018471[1] = {&ui_img_1423884986};
const lv_img_dsc_t * ui_imgset_1766742700[1] = {&ui_img_789797763};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void contentSwitching_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_config_screen_init);
    }
}

void ui_event_layoutBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_main_screen_init);
    }
}

void ui_event_Switch6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_Slider4, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 100);
    }
}

void ui_event_Switch9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_Slider9, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 100);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Temp, target, "", "°C");
    }
}

void ui_event_Btn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_ContentLight, 0);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Btn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_ContentScene, 0);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Btn8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_groupCurtain, 0);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Btn9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_ContentHVAC, 0);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Btn10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_GroupBlank, 0);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Btn11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_GroupBlank, 0);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Btn13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_GroupBlank, 0);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Btn14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentLight, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentScene, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupCurtain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContentHVAC, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_GroupBlank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        contentSwitching_Animation(ui_GroupBlank, 0);
        _ui_flag_modify(ui_menuSelected11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuSelected14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuSelected13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_config_screen_init);
    }
}

void ui_event_setting1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_config_screen_init);
    }
}

void ui_event_layoutBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_main_screen_init);
    }
}

void ui_event_configBrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        config_set_backlight(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_Slider4, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 100);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_config_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
