// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "ui.h"
#include <Arduino.h>
#include "../../modbus/modbus.h"

void config_set_backlight(lv_event_t * e)
{
	lv_obj_t *slider = lv_event_get_target(e);
	float brightness = 100.0;
	if (slider == ui_configBrightnessSlider)
    {
        brightness = (float)lv_slider_get_value(slider)/100.0;
		// 0 is off, 0.5 is half and 1 is full brightness.
    }
	
}

void DeskLightSwitch(lv_event_t * e)
{
	// Your code here
	lv_obj_t * switcher = lv_event_get_target(e);
	if (switcher == ui_Switch3)
    {
		const uint16_t data[] = {0x0002};
    	const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
		const uint16_t start_address = 32;
		modbus_client_set_parameters(data, start_address, num_registers);
    }
}

void WallLightSwitch(lv_event_t * e)
{
	// Your code here
	lv_obj_t * switcher = lv_event_get_target(e);
	if (switcher == ui_Switch4)
    {
		const uint16_t data[] = {0x0002};
    	const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
		const uint16_t start_address = 33;
		modbus_client_set_parameters(data, start_address, num_registers);
    }
}

void CircleLedSwitch(lv_event_t * e)
{
	// Your code here
	lv_obj_t * switcher = lv_event_get_target(e);
	if (switcher == ui_Switch7)
    {
		const uint16_t data[] = {0x0002};
    	const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
		const uint16_t start_address = 34;
		modbus_client_set_parameters(data, start_address, num_registers);
    }
}

void PendantLedSwitch(lv_event_t * e)
{
	// Your code here
	lv_obj_t * switcher = lv_event_get_target(e);
	if (switcher == ui_Switch8)
    {
		const uint16_t data[] = {0x0002};
    	const uint16_t num_registers = sizeof(data) / sizeof(data[0]);
		const uint16_t start_address = 35;
		modbus_client_set_parameters(data, start_address, num_registers);
    }
}

void CeilingLedSlider(lv_event_t * e)
{
	// Your code here
}

void CeilingLightSlider(lv_event_t * e)
{
	// Your code here
}
