// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#include "ui.h"
#include <string.h>
#include <stdio.h>


typedef enum {
	COFFEE_ESPRESSO = 0,
	COFFEE_AMERICANO,
	COFFEE_LATTE,
	COFFEE_IRISH,
	COFFEE_MACCHIATO,
	COFFEE_CREAM
} CoffeeType;


// Use a struct to hold QR code data and object for better organization
typedef struct {
    lv_obj_t * qr_code;
    char data[100]; // Increased size for longer QR codes
} QRCodeData;

static QRCodeData qr_code_data; // Initialize globally
static CoffeeType selected_coffee = COFFEE_ESPRESSO;
static lv_timer_t * status_timer = NULL; 

CoffeeType get_selected_coffee_type() {
    return selected_coffee;
}

// Function to generate a QR code with error handling
lv_obj_t * generate_qr_code(const char * text, uint16_t size) {
    lv_obj_t * qr = lv_qrcode_create(lv_scr_act(), size, lv_color_hex3(0x000), lv_color_hex3(0xFFF));
    if (qr == NULL) {
        // Handle error: QR code creation failed.  Log the error or display a message.
        printf("Error creating QR code\n"); //Example error handling
        return NULL;
    }
    lv_qrcode_update(qr, text, strlen(text));
    return qr;
}

void generate_qr_code_for_coffee(CoffeeType coffeeType) {
    // Delete existing QR code if any
    if (qr_code_data.qr_code != NULL) {
        lv_obj_del(qr_code_data.qr_code);
        qr_code_data.qr_code = NULL;
    }
	switch (coffeeType) {
		case COFFEE_ESPRESSO:
			sprintf(qr_code_data.data, "Hello, Boss Mo");
			break;
		case COFFEE_AMERICANO:
			sprintf(qr_code_data.data, "when can we be able to earn 1 million RMB");
			break;
		case COFFEE_LATTE:
			sprintf(qr_code_data.data, "for each person?");
			break;
		case COFFEE_IRISH:
			sprintf(qr_code_data.data, "Irish Coffee - $5.99");
			break;
		case COFFEE_MACCHIATO:
			sprintf(qr_code_data.data, "when can we be able to earn 1 million RMB for each person?");
			break;
		case COFFEE_CREAM:
			sprintf(qr_code_data.data, "Boss Mo Fighting!!");
			break;
		default:
			strcpy(qr_code_data.data, "Unknown Item");
			break;
	}
}


void button_espresso(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Espresso");
    lv_label_set_text(ui_Label_Price, "2.99");
	generate_qr_code_for_coffee(COFFEE_ESPRESSO);
	selected_coffee = COFFEE_ESPRESSO;
}

void button_americano(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Americano");
    lv_label_set_text(ui_Label_Price, "3.99");
	generate_qr_code_for_coffee(COFFEE_AMERICANO);
	selected_coffee = COFFEE_AMERICANO;
}

void button_latte(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Latte");
    lv_label_set_text(ui_Label_Price, "4.50");
	generate_qr_code_for_coffee(COFFEE_LATTE);
	selected_coffee = COFFEE_LATTE;
}

void button_irish(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Irish Coffee");
    lv_label_set_text(ui_Label_Price, "5.99");
	generate_qr_code_for_coffee(COFFEE_IRISH);
	selected_coffee = COFFEE_IRISH;
}

void button_Macchiato(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Macchiato Coffee");
    lv_label_set_text(ui_Label_Price, "6.99");
	generate_qr_code_for_coffee(COFFEE_MACCHIATO);
	selected_coffee = COFFEE_MACCHIATO;
}

void button_cream(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Lattee with cream Coffee");
    lv_label_set_text(ui_Label_Price, "7.99");
	generate_qr_code_for_coffee(COFFEE_CREAM);
	selected_coffee = COFFEE_CREAM;
}


void Payment_screen_loaded(lv_event_t * e) {
    qr_code_data.qr_code = generate_qr_code(qr_code_data.data, 230); // Use the improved function

	if (qr_code_data.qr_code != NULL) { // Check for NULL after generation
		lv_obj_set_parent(qr_code_data.qr_code, ui_QRCodeCanvas);
		lv_obj_center(qr_code_data.qr_code);
	}
    if (qr_code_data.qr_code == NULL) {
        printf("Error generating QR code in Payment_screen_loaded\n");
        return;
    }
}

void set_coffee_image_visibility(lv_obj_t * visible_image) {
    // Hide both images
    lv_obj_add_flag(ui_img_coffee, LV_OBJ_FLAG_HIDDEN);  // Hide ui_img_coffee
    lv_obj_add_flag(ui_img_coffee1, LV_OBJ_FLAG_HIDDEN); // Hide ui_img_coffee1

    // Show the selected image
    if (visible_image != NULL) {
        lv_obj_clear_flag(visible_image, LV_OBJ_FLAG_HIDDEN);
    }
}

// Callback function to update the status label
void update_status_label(lv_timer_t * timer) {
    lv_label_set_text(ui_Label_Status, "Ready, please take your drink");
} 

void Prep_screen_loaded(lv_event_t * e) {
    CoffeeType coffeeType = get_selected_coffee_type();

    // Update the status label
    lv_label_set_text(ui_Label_Status, "Preparing your drink");

    // Hide both sets of coffee images, masks, and glasses initially
    lv_obj_add_flag(ui_img_coffee, LV_OBJ_FLAG_HIDDEN);  // Hide ui_img_coffee
    lv_obj_add_flag(ui_Image_mask, LV_OBJ_FLAG_HIDDEN);  // Hide ui_Image_mask
    lv_obj_add_flag(ui_Img_glass, LV_OBJ_FLAG_HIDDEN);   // Hide ui_Img_glass

    lv_obj_add_flag(ui_img_coffee1, LV_OBJ_FLAG_HIDDEN); // Hide ui_img_coffee1
    lv_obj_add_flag(ui_Image_mask1, LV_OBJ_FLAG_HIDDEN); // Hide ui_Image_mask1
    lv_obj_add_flag(ui_Img_glass1, LV_OBJ_FLAG_HIDDEN);  // Hide ui_Img_glass1

	lv_obj_add_flag(ui_img_coffee2, LV_OBJ_FLAG_HIDDEN);
	
    // Determine which set of objects to show based on the selected coffee type
    lv_obj_t * coffee_image = NULL;
    lv_obj_t * mask = NULL;
    lv_obj_t * glass = NULL;
	uint16_t animation_duration = 10000;

    switch (coffeeType) {
        case COFFEE_ESPRESSO:
        case COFFEE_AMERICANO:
            coffee_image = ui_img_coffee;
            mask = ui_Image_mask;
            glass = ui_Img_glass;
            break;
        case COFFEE_IRISH:
			coffee_image = ui_img_coffee2;
            mask = ui_Image_mask1;
            glass = ui_Img_glass1;
			break;
	    case COFFEE_LATTE:
        case COFFEE_MACCHIATO:
        case COFFEE_CREAM:
            coffee_image = ui_img_coffee1;
            mask = ui_Image_mask1;
            glass = ui_Img_glass1;
            break;
        default:
            break;
    }


    // Show the selected set of objects
    if (coffee_image != NULL && mask != NULL && glass != NULL) {
        lv_obj_clear_flag(coffee_image, LV_OBJ_FLAG_HIDDEN); // Show the selected coffee image
        lv_obj_clear_flag(mask, LV_OBJ_FLAG_HIDDEN);        // Show the selected mask
        lv_obj_clear_flag(glass, LV_OBJ_FLAG_HIDDEN);       // Show the selected glass
    }

	if (coffee_image != NULL && mask != NULL && glass != NULL) {
        lv_anim_t a;
        lv_anim_init(&a);
        lv_anim_set_var(&a, coffee_image); // Apply animation to the selected image
        lv_anim_set_time(&a, animation_duration);      // Animation duration: 7 seconds
        lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y); // Animate the Y position 

		switch (coffeeType) {
			case COFFEE_ESPRESSO:
				animation_duration = 11000;
				lv_anim_set_values(&a, 135, 40);
			break;
			case COFFEE_AMERICANO:
				animation_duration = 11000;
				lv_anim_set_values(&a, 135, 40);
            break;
			case COFFEE_LATTE:
				animation_duration = 11000;
				lv_anim_set_values(&a, 215, 60);
				break;
			case COFFEE_IRISH:
				animation_duration = 13000;
				lv_anim_set_values(&a, 215, 40);
				break;
			case COFFEE_MACCHIATO:
				animation_duration = 13000;
				lv_anim_set_values(&a, 215, 60);
				break;
			case COFFEE_CREAM:
				animation_duration = 13000;
				lv_anim_set_values(&a, 215, 60);
				break;
			default:
				animation_duration = 7000; // Default duration
				lv_anim_set_values(&a, 135, 40);
				break;
		}
		lv_anim_start(&a);
	}

    if (status_timer != NULL) {
        lv_timer_del(status_timer); // Delete the timer
        status_timer = NULL;        // Reset the timer handle
    }

	status_timer = lv_timer_create(update_status_label, animation_duration, NULL);
}
