// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void config_set_backlight(lv_event_t * e);
void DeskLightSwitch(lv_event_t * e);
void WallLightSwitch(lv_event_t * e);
void CircleLedSwitch(lv_event_t * e);
void PendantLedSwitch(lv_event_t * e);
void CeilingLedSlider(lv_event_t * e);
void CeilingLightSlider(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
