// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SmartPanel

#include "ui.h"
#include <Arduino.h>

void config_set_backlight(lv_event_t * e)
{
	lv_obj_t *slider = lv_event_get_target(e);
	float brightness = 100.0;
	if (slider == ui_configBrightnessSlider)
    {
        brightness = (float)lv_slider_get_value(slider)/100.0;
		// 0 is off, 0.5 is half and 1 is full brightness.
    }
	
}
